//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelDBEntities1 : DbContext
    {
        public TravelDBEntities1()
            : base("name=TravelDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<destination> destinations { get; set; }
        public virtual DbSet<offer> offers { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
