//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;


    public partial class user
    {
        [Required, DataType(DataType.EmailAddress)]
        public string email { get; set; }
        [Required]
        public string fname { get; set; }
        [Required]
        public string lname { get; set; }
        [Required]
        public string password { get; set; }
        [Required]
        public string qID { get; set; }
        [Required]
        public string answer { get; set; }
        public string type { get; set; }
        [Required]
        public string uname { get; set; }
        [Required]
        public string imgpath { get; set; }

        internal void Session_Start(user u)
        {
            HttpContext.Current.Session["User Name"] = u.uname;
            HttpContext.Current.Session["First Name"] = u.fname;
            HttpContext.Current.Session["Last Name"] = u.lname;
            HttpContext.Current.Session["Email"] = u.email;
            HttpContext.Current.Session["Password"] = u.password;
            HttpContext.Current.Session["ImagePath"] = u.imgpath;
        }
    }
}
